language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
cache:
  directories:
    - /Users/travis/.rvm/
    - /Users/travis/Downloads/
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- travis_wait 30 ./Scripts/build.sh
deploy:
  - provider: pages
    github-token:
      secure: $GITHUB_OAUTH_TOKEN
    local-dir: ./Build/webgl
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
